### ISSUE TITLE
Battle Tiers outdated / misfunctioning.

### ISSUE THREAD

**Issue by Nullmaruzero** [smellyriver/tankinspector#9]
The Battle Tier data used by STI is older than my grandfather and due to that age it started to fall apart.

In short: 

- I fixed the names by updating all the TAG-names (only UK and China had nation prefixes (like GB02_ , Ch03_) so only special tanks of these two nations were displayed properly).
- Updated the file for the new MM for light tanks, added LTs of Tier IX and X.
- Added some missing tanks with preferential MM (how could you forget to add M6A2E1 a.k.a "The Potato"?)
- Added Battle Tier XII again, since now it is again possible to have exclusive Tier X vs Tier X battles. STI seems to work fine with it.
- Removed some tanks which are no longer valid or died of old age. Like our beloved Karl :( [*]

Feel free to review my changes. I use Issue Tracker because I did not touch the code at all, I merely edited the .xml file and as far as my quick testing goes, STI seems to work fine but I cannot promise it won't cause some bugs :)

[Additional.zip](https://github.com/smellyriver/tankinspector/files/1072532/Additional.zip)

Now, some TL;DR.
I had problems getting reliable battle tier data for tanks with preferential matchmaking. WG keeps their wiki outdated (why bother, chat moderators redirect new players to it only 2000 times a day. Yummy out-of-date data!), the game does not show battle tier (I have some mods for that, but it works only for the tanks I currently own. I cannot fetch the data for tanks I do not have) and WOT API does not seem to have it. Fetched everything as far as a tank object goes and did not find anything useful (other than the TAG names, which let me fix the names). I used WG's wiki anyway, because after all tanks with preferential MM seem to be a thing of the past so it should be pretty ok. But it could be that some of the special-snowflake tanks have wrong MM put in.

I also could not find some tanks in the API, like T-44-85 (which was listed in the .xml) and Type 59 Gold.
T-44-85 I removed since not even WoT Wiki knows anything about that and I have read somewhere that it was a supertest tank which has never been introduced.
Type 59 Gold I left in the files since I assumed it might be some exclusive for Asia region. You guys always get over-the-top tanks there xD

P.S
If you decide to update the camo system (because it shows total BS and the structure of the .xml for camo does not even seem to reflect current camo mechanic) I could help by doing the legwork and collecting the camo values from the game for different tanks (including different modules, because it differs). I don't suppose there is any easy and fast way for fetching it? At least now it is in the game client and the new comparator is a handy tool :)

**Comment by hillin** [comment]
Thanks @Nullmaruzero, this is very helpful. The battle tier data is indeed very ancient.
As I'm no longer a WoT player nowadays, I'll simply put your work into the source code, trust your data, do some simple test to ensure nothing goes wrong too badly, and ship it with the next release. The data is always open to review, anyone can improve it like you did, which is the whole point of open source.

As for the camo system, [Tank Inspector is already using the in-game *invisibility* values](https://github.com/smellyriver/tankinspector/blob/master/TankInspector/Modeling/Tank/Tank.cs#L36-L37), the XML file is just a fallback to compat with pre-9.15 game clients, which I believe can be removed now, along with some other branches to support older game versions in the codebase.  I guess there might be some formula issue if the values displayed mismatch with the in-game display.

Oh and it would be even better if we can do things in GitHub way, like making [Pull Requests](https://help.github.com/articles/about-pull-requests/) instead of posting source code directly. There are numerous advantages to this if you are aware - it's easier to integrate your changes, we can have better tools to review it, and you can leave your name in the version history (if you care about that 😆).

**Comment by hillin** [comment]
I'm closing this issue, if you have any further question about the camo system, please open another issue.
